name: CI

on: [push]

jobs:
  test:
    name: Test
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and test
        run: |
          xcodebuild clean test -project AaaaaandAction.xcodeproj -scheme AaaaaandActionTests -destination "platform=iOS Simulator,name=iPhone 8"
          bash <(curl -s https://codecov.io/bash)

